### ISSUE TITLE
Link not working: http://lager.cs.uni-duesseldorf.de/NLP/IWNLP/IWNLP.Lemmatizer_20181001.zip

### ISSUE THREAD

**Issue by dominikmn** [Liebeck/IWNLP-py#5]
Hi, the following path seems to be unavailable `http://lager.cs.uni-duesseldorf.de/NLP/IWNLP/IWNLP.Lemmatizer_20181001.zip`
I encounter this issue by following the setup instruction in the [README.md](https://github.com/Liebeck/IWNLP-py/blob/master/README.md). Would be great if you have another temporary resource such that I can make my notebook work again :)

**Comment by Liebeck** [comment]
@dominikmn The issue with our server has been fixed and the file is now available again ;) Sorry for the inconvenience!

**Comment by dominikmn** [comment]
Thanks :)
